### ISSUE TITLE
error when running Terraform plan

### ISSUE THREAD

**Issue by cgriggs01** [alibaba/terraform-alicloud-ecs-instance#3]
I am testing these modules for the Terraform Module Registry and came upon an error.

"io_optimized": required field is not set

this was fixed by adding this to main.tf alicloud_instance resource.
io_optimized = "none"

**Comment by xiaozhu36** [comment]
Hi @cgriggs01 

We have deprecated the field 'io_optimized' from [terraform-provider-alicloud](https://github.com/alibaba/terraform-provider/releases), but terraform does not merge my [PR](https://github.com/terraform-providers/terraform-provider-alicloud/pull/11). 
I have declared it in the README, thanks.

Regards,
He Guimin

**Comment by roura356a** [comment]
This is still giving errors.

**Comment by xiaozhu36** [comment]
Hi @roura356a 

I am sorry for that. Can you please show the error details? thanks.

Regards,
He Guimin

**Comment by roura356a** [comment]
Well, this only happens using the official alicloud provider from terraform. Works fine using the one provided by alibaba, so all good!

**Comment by cgriggs01** [comment]
Hi He,

I'm checking in on this module to see if this was resolved since the [PR](https://github.com/terraform-providers/terraform-provider-alicloud/pull/11) was merged into the [terraform-provider-alibaba](https://github.com/terraform-providers/terraform-provider-alibaba) repo.

I was still unable to run `terraform plan` successfully and getting the same io_opimized missing error.

Any thoughts? I would like to make sure that all of the provider builds hosted by HachiCorp work correctly with the all verified modules that reference it.

Best,
Chris

**Comment by xiaozhu36** [comment]
Hi @cgriggs01 @roura356a If you still have any problem about the issue, please reopen the issue. Thanks a lot.

**Comment by roura356a** [comment]
Thanks @xiaozhu36. For me this happened for not using the provider from Alibaba github. All good for me =)
