### ISSUE TITLE
Provider doesn't support resource: alicloud_key_pair_attchment

### ISSUE THREAD

**Issue by nellieli** [alibaba/terraform-alicloud-ecs-instance#8]
Provider does not support 
alicloud_key_pair_attchment

Please change to provided supported  "attachment" with an a
alicloud_key_pair_attachment

https://www.terraform.io/docs/providers/alicloud/r/key_pair_attachment.html
resource "alicloud_key_pair_attachment" "attach" {
  key_name = "${alicloud_key_pair.key.id}"
  instance_ids = ["${alicloud_instance.instance.*.id}"]
}

**Comment by zzxwill** [comment]
It's supported. http://47.95.33.19:4567/docs/providers/alicloud/r/key_pair_attachment.html
The resource name is alicloud_key_pair_attachment.

**Comment by xiaozhu36** [comment]
Hi @zzxwill thanks for your reply.
